[package]
edition = "2024"
name = "fileserver"
version = "0.1.0"
authors = ["Michael Schöttner <michael.schoettner@hhu.de>, Fabian Ruhland <ruhland@hhu.de>"]

[lib]
crate-type = ["staticlib"]
path = "src/fileserver.rs"

[dependencies]
# Local dependencies
runtime = { path = "../../library/runtime" }
terminal = { path = "../../library/terminal" }
time = { path = "../../library/time" }
concurrent = { path = "../../library/concurrent" }
naming = { path = "../../library/naming" }
syscall = { path = "../../library/syscall" }
log = "0.4.27"
spin = "0.10.0"
bitflags = "1.3.2"